<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MovingHeadSequencer\MovingHeadSequencer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="publish\**\*" />
    <None Remove="publish\**\*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);publish\**</DefaultItemExcludes>
  </PropertyGroup>

</Project>
