<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MovingHeadSequencer\MovingHeadSequencer.csproj" />
    <ProjectReference Include="..\MovingHeadSequencer.Web\MovingHeadSequencer.Web.csproj" />
  </ItemGroup>

</Project>
